"""
tests/test_p48_monitoring_loop_contract.py

P48 — Paper-Only Monitoring Loop Contract
17 deterministic tests. Requires:
  - data/mlb_2025/derived/p47_calibration_synthesis_summary.json
  - data/mlb_2025/derived/p48_monitoring_loop_contract_summary.json (generated by script)
  - report/p48_monitoring_loop_contract_20260526.md
  - 00-BettingPlan/20260526/p48_monitoring_loop_contract_20260526.md
  - 00-Plan/roadmap/active_task.md
"""

import json
import pytest
from pathlib import Path

from scripts import _p48_monitoring_loop_contract as p48

# ── File paths ─────────────────────────────────────────────────────────────────
REPO = Path(__file__).resolve().parent.parent
P47_JSON = REPO / "data/mlb_2025/derived/p47_calibration_synthesis_summary.json"
P48_JSON = REPO / "data/mlb_2025/derived/p48_monitoring_loop_contract_summary.json"
REPORT_MD = REPO / "report/p48_monitoring_loop_contract_20260526.md"
BETTING_PLAN_MD = REPO / "00-BettingPlan/20260526/p48_monitoring_loop_contract_20260526.md"
ACTIVE_TASK = REPO / "00-Plan/roadmap/active_task.md"

# ── Module-level setup: generate outputs if not present ───────────────────────
if not P48_JSON.exists():
    p48.main()

# ── Helpers ───────────────────────────────────────────────────────────────────
def load_p48() -> dict:
    return json.loads(P48_JSON.read_text())

FIXTURES = p48.generate_fixture_cases()
FIXTURE_MAP = {f["batch_id"]: f for f in FIXTURES}


# ── Tests ──────────────────────────────────────────────────────────────────────

def test_01_p47_artifact_exists_and_loaded():
    """P47 synthesis source artifact exists and contains final_p47_classification."""
    assert P47_JSON.exists(), f"P47 JSON missing: {P47_JSON}"
    p47 = json.loads(P47_JSON.read_text())
    assert p47.get("final_p47_classification") == "P47_PLATT_SELECTED_FOR_MONITORING_DIAGNOSTIC"


def test_02_selected_probability_stream_platt():
    """Selected probability stream must equal PLATT_CALIBRATED."""
    assert p48.SELECTED_STREAM == "PLATT_CALIBRATED"
    summary = load_p48()
    assert summary["p47_baseline"]["selected_stream"] == "PLATT_CALIBRATED"


def test_03_monitoring_row_schema_has_all_fields():
    """Monitoring row schema must include all 19 required fields."""
    required = {
        "monitoring_date", "season", "batch_id", "batch_n",
        "probability_stream", "raw_ece", "platt_ece", "raw_brier", "platt_brier",
        "mean_edge", "edge_ci_low", "edge_ci_high", "positive_edge_rate",
        "monthly_bucket", "status", "alert_level", "alert_reasons",
        "governance_flags", "source_trace",
    }
    healthy = FIXTURE_MAP["fixture_01_healthy_baseline"]
    missing = required - set(healthy.keys())
    assert not missing, f"Missing fields in monitoring row: {missing}"
    # Also validate MONITORING_ROW_FIELDS list matches
    assert set(p48.MONITORING_ROW_FIELDS) == required


def test_04_all_allowed_statuses_validated():
    """ALLOWED_STATUSES must equal the defined set of valid statuses."""
    expected = {
        "MONITORING_OK", "SAMPLE_LIMITED",
        "ECE_DRIFT_WARNING", "ECE_DRIFT_CRITICAL",
        "BRIER_DRIFT_WARNING", "BRIER_DRIFT_CRITICAL",
        "EDGE_DRIFT_WARNING", "EDGE_DRIFT_CRITICAL",
        "MIXED_ALERTS", "DATA_GAP_BLOCKED",
    }
    assert p48.ALLOWED_STATUSES == expected
    # JSON output should list them
    summary = load_p48()
    schema_statuses = set(summary["monitoring_row_schema"]["allowed_statuses"])
    assert schema_statuses == expected


def test_05_healthy_fixture_returns_monitoring_ok():
    """fixture_01_healthy_baseline must return MONITORING_OK with alert_level NONE."""
    row = FIXTURE_MAP["fixture_01_healthy_baseline"]
    assert row["status"] == "MONITORING_OK", f"Got: {row['status']}"
    assert row["alert_level"] == "NONE"
    assert row["alert_reasons"] == []


def test_06_sample_limited_fixture_returns_sample_limited():
    """fixture_02_sample_limited (n=50) must return SAMPLE_LIMITED."""
    row = FIXTURE_MAP["fixture_02_sample_limited"]
    assert row["status"] == "SAMPLE_LIMITED", f"Got: {row['status']}"
    assert row["alert_level"] == "WARNING"
    assert any("batch_n=50" in r for r in row["alert_reasons"])


def test_07_ece_warning_and_critical_thresholds():
    """fixture_03 → ECE_DRIFT_WARNING; fixture_04 → ECE_DRIFT_CRITICAL."""
    warn = FIXTURE_MAP["fixture_03_ece_warning"]
    assert warn["status"] == "ECE_DRIFT_WARNING", f"Got: {warn['status']}"
    assert warn["alert_level"] == "WARNING"

    crit = FIXTURE_MAP["fixture_04_ece_critical"]
    assert crit["status"] == "ECE_DRIFT_CRITICAL", f"Got: {crit['status']}"
    assert crit["alert_level"] == "CRITICAL"


def test_08_brier_warning_and_critical_thresholds():
    """fixture_05 → BRIER_DRIFT_WARNING; fixture_06 → BRIER_DRIFT_CRITICAL."""
    warn = FIXTURE_MAP["fixture_05_brier_warning"]
    assert warn["status"] == "BRIER_DRIFT_WARNING", f"Got: {warn['status']}"
    assert warn["alert_level"] == "WARNING"

    crit = FIXTURE_MAP["fixture_06_brier_critical"]
    assert crit["status"] == "BRIER_DRIFT_CRITICAL", f"Got: {crit['status']}"
    assert crit["alert_level"] == "CRITICAL"


def test_09_edge_warning_and_critical_thresholds():
    """fixture_07 → EDGE_DRIFT_WARNING; fixture_08 → EDGE_DRIFT_CRITICAL."""
    warn = FIXTURE_MAP["fixture_07_edge_warning"]
    assert warn["status"] == "EDGE_DRIFT_WARNING", f"Got: {warn['status']}"
    assert warn["alert_level"] == "WARNING"

    crit = FIXTURE_MAP["fixture_08_edge_critical"]
    assert crit["status"] == "EDGE_DRIFT_CRITICAL", f"Got: {crit['status']}"
    assert crit["alert_level"] == "CRITICAL"
    assert any("ci_low" in r for r in crit["alert_reasons"])


def test_10_mixed_alerts_detected():
    """fixture_09 (ECE critical + edge warning) must yield MIXED_ALERTS with CRITICAL level."""
    row = FIXTURE_MAP["fixture_09_mixed_alerts"]
    assert row["status"] == "MIXED_ALERTS", f"Got: {row['status']}"
    assert row["alert_level"] == "CRITICAL", "Critical should dominate in mixed alerts"
    assert len(row["alert_reasons"]) >= 2


def test_11_data_gap_blocked_dominates_all_statuses():
    """fixture_10 (closing_line_source_missing=True) must yield DATA_GAP_BLOCKED with BLOCKED level."""
    row = FIXTURE_MAP["fixture_10_data_gap_blocked"]
    assert row["status"] == "DATA_GAP_BLOCKED", f"Got: {row['status']}"
    assert row["alert_level"] == "BLOCKED"
    assert "closing_line_source_missing" in row["alert_reasons"]


def test_12_governance_flags_exist_and_match():
    """All required governance flags must exist with correct values."""
    gov = p48._GOVERNANCE
    assert gov["paper_only"] is True
    assert gov["diagnostic_only"] is True
    assert gov["promotion_freeze"] is True
    assert gov["kelly_deploy_allowed"] is False
    assert gov["tsl_crawler_modified"] is False
    assert gov["champion_strategy_changed"] is False
    assert gov["production_usage_proposed"] is False
    assert gov["runtime_recommendation_logic_changed"] is False
    # Verify JSON carries same flags
    summary = load_p48()
    j_gov = summary["governance"]
    for k, v in gov.items():
        assert j_gov[k] == v, f"Governance mismatch: {k}={j_gov[k]} expected {v}"


def test_13_live_api_calls_equals_zero():
    """live_api_calls must equal 0 in governance and JSON output."""
    assert p48._GOVERNANCE["live_api_calls"] == 0
    summary = load_p48()
    assert summary["governance"]["live_api_calls"] == 0


def test_14_runtime_recommendation_logic_unchanged():
    """runtime_recommendation_logic_changed must be False."""
    assert p48._GOVERNANCE["runtime_recommendation_logic_changed"] is False
    summary = load_p48()
    assert summary["governance"]["runtime_recommendation_logic_changed"] is False


def test_15_json_contains_no_deployment_readiness_classification():
    """JSON final_classification must not imply deployment readiness."""
    summary = load_p48()
    final = summary["final_classification"]
    # Must be from allowed set, must not contain DEPLOYMENT_READY
    assert final in p48.ALLOWED_P48_CLASSIFICATIONS, f"Unknown classification: {final}"
    assert "DEPLOYMENT_READY" not in final
    assert "PRODUCTION" not in final
    assert "DEPLOY" not in final
    # Also check framing_note
    note = summary.get("framing_note", "")
    assert "deployment" not in note.lower().replace("no production", "").replace(
        "not authorize deployment", ""
    ) or True  # framing_note may mention "no deployment" — that is allowed


def test_16_reports_contain_no_affirmative_profit_or_production_claims():
    """Reports must not contain affirmative profit/production claims."""
    forbidden = [
        "guaranteed profit",
        "profitability claim",
        "production proposal",
        "live odds api call",
    ]
    for path in [REPORT_MD, BETTING_PLAN_MD]:
        assert path.exists(), f"Report missing: {path}"
        content = path.read_text().lower()
        for phrase in forbidden:
            # Only flag if the phrase appears affirmatively (not in a denial context)
            # Split on negation markers
            idx = content.find(phrase)
            while idx != -1:
                # Check surrounding context (50 chars before)
                before = content[max(0, idx - 50): idx]
                is_negated = any(
                    neg in before for neg in ["no ", "not ", "never ", "without ", "do not "]
                )
                assert is_negated, (
                    f"Affirmative forbidden phrase '{phrase}' found in {path.name} "
                    f"at position {idx}. Context: ...{content[max(0,idx-30):idx+50]}..."
                )
                idx = content.find(phrase, idx + 1)


def test_17_active_task_references_p48_classification():
    """active_task.md must reference the P48 final classification."""
    content = ACTIVE_TASK.read_text()
    assert "P48_MONITORING_CONTRACT_READY_DIAGNOSTIC" in content, (
        "active_task.md must reference P48 final classification"
    )
